Bloco D - Desenvolvimento .Net/KeepEverything.RaysaDutra/KeepEverything.Consumer.RaysaDutra/KeepEverything.Consumer.RaysaDutra/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace KeepEverything.Consumer.RaysaDutra.Controllers
{
    public class TasksController : Controller
    {
        
        // GET: Tag
        public ActionResult Tag()
        {
            return View();
        }

        // GET: Category
        public ActionResult Category()
        {
            return View();
        }
    }
}

Bloco D - Desenvolvimento .Net/KeepEverything.RaysaDutra/KeepEverything.Consumer.RaysaDutra/KeepEverything.Consumer.RaysaDutra/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Keep Everything", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Tag", "Tag", "Tasks", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Categoria", "Category", "Tasks", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Created by <a href="http://contactup.io/_u1276/">Raysa Dutra</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>